### ISSUE TITLE
White screen rendering when given options

### ISSUE THREAD

**Issue by steoneill** [Agezao/confetti-generator#1]
Hi there!

If I render this with other options in the main object, it renders a white screen using react.

I also get the below error :

index.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'getContext' of null
    at new ./node_modules/confetti-js/dist/index.min.js.window.ConfettiGenerator (index.min.js:1)

**Comment by Agezao** [comment]
Hi!
Can you give more context abou what you're trying to achieve?
Some code snippets would be helpful too.

It looks like confetti-js is not able to find the `<canvas>` to bind too...

**Comment by steoneill** [comment]
Hi there, thanks for the super quick response!

I followed your examples to get it as a stateless component, but i've changed it to have state and a componentDidMount and that's actually seemed to fix it!

You're a star, and will receive one in a tick!

**Comment by Agezao** [comment]
Nice to hear that it worked. So, can I close the issue?

For context, if someone happen to struggle with the same problem in the future, this is usually what I do when using confetti-js with React:

At the component I want to use confetti-js:

```
...
// Importing confetti-js
import "../../../../node_modules/confetti-js/dist/index.min.js";
...
class MyComponent extends Component {
 // Adding a it to my state
  state = {
    confetti: null
  }

 // Initializing it
  componentDidMount() {
    let confetti = new window.ConfettiGenerator();
    confetti.render();
    this.setState({confetti: confetti});
  }

  // Destroying it
  componentWillUnmount() {
    this.state.confetti.clear();
    this.setState({confetti: null});
  }

  render() {
    return (
            <div className="confetti">
              <canvas id="confetti-holder"></canvas>
            </div>
    );
  }
}
```
