### ISSUE TITLE
Ionic issue

### ISSUE THREAD

**Issue by elepetit** [Agezao/confetti-generator#24]
Hi,
This works good in ionic4 but not managed to render prop->svg
Someone to help me?

thx

**Comment by elepetit** [comment]
const confettiSettings = {
      target: 'my-canvas',
      max: 200,
      size: 1.8,
      animate:true,
      "props": [
        "circle",
        { "type": "svg", "src": "assets/hat.svg","size":25,"weight":2 }
      ],
      rotate: true};

**Comment by rbrand21** [comment]
Ever figure this out? I'm seeing a similar issue on Safari and iOS Safari.
The odd thing is that when I go to https://agezao.github.io/confetti-js/ on Safari, the hat.svg does show up.

But when I run my application locally with my svgs, they don't show up. Seems to indicate something with Ionic?

**Comment by Agezao** [comment]
Can you double-check if your app have access to the src of the image?

**Comment by rbrand21** [comment]
Tried the hat.svg in my own project (thinking it could be an svg metadata issue on Safari) - no luck.
Tried stepping through the code where `new window.Image()` is called and everything appears to be fine.

**Comment by rbrand21** [comment]
> Can you double-check if your app have access to the src of the image?

It does. I went to `http://localhost:8100/assets/<mysvg>.svg` and it loads in a different browser tab (on Safari).
From what I can tell, everything looks good there:
![image](https://user-images.githubusercontent.com/5422292/86663468-9b570500-bfa2-11ea-86bb-a6bef2a8aebc.png)

**Comment by rbrand21** [comment]
@Agezao Any other suggestions? Thanks for this library btw. 👌

**Comment by Agezao** [comment]
Well, interesting.

To narrow down our troubleshoot, can you try to reference an external image? (for example, use this url on the reference: https://agezao.github.io/confetti-js/site/hat.svg )

And, also, can you check the network log or the console output for the app to see if there're any hint of what could be happening?

**Comment by rbrand21** [comment]
Interesting, so I used the hat image link you provided and that did work! So something to do with grabbing the files locally on Ionic seems to not be working correctly.

**Comment by Agezao** [comment]
Hi, sorry for the radio silence here.

Did you manage to figure it out? Given that using an absolute URL (with HTTP, etc) it worked, your troubleshoot looks on point: looks like a problem on the image `src` reference of your project.

May I be of any assistance?

_(I'm closing this beforehand)_

**Comment by rbrand21** [comment]
I have not figured it out still. I haven't really found any documentation of referencing asset files from .ts in Ionic. But, using the same file path that is used typically in .html src attributes was not working.
