### ISSUE TITLE
Spawn positions

### ISSUE THREAD

**Issue by mrjacobbloom** [Agezao/confetti-generator#6]
A couple minor things I noticed with spawn positions:

- If the size is big enough, parts of the confetti are still on screen when they appear and disappear
- if the clock is set to a negative number they animate backwards but don't restart when they reach the top

**Comment by Agezao** [comment]
Hi!

Thanks for the report.
1. About the negative clock -> Fix'd

2. About the particle "dissapearing", it's easily fixed with a smaller container for a bigger `<canvas>`. Like the example bellow:
https://jsfiddle.net/6gbvLqc9/14/
