### ISSUE TITLE
Reference Error: window is not defined in Nuxtjs

### ISSUE THREAD

**Issue by ibnujakaria** [Agezao/confetti-generator#7]
I tried `confetti-js` in nuxtjs with both enabled and disabled ssr and still got this error.

<img src="https://image.ibb.co/dURDM9/Screenshot_from_2018_10_11_15_04_45.png" alt="Screenshot_from_2018_10_11_15_04_45" border="0">

**Comment by Agezao** [comment]
Hello there,
Can you give more context about the issue?
It would be great if I could have some steps to reproduce...

Looking forward for a feedback!

**Comment by Agezao** [comment]
Closing after 20 days of inactivity.
If you stumble on the same problem again, feel free to re-open the issue with steps to reproduce and we can further discuss.
