### ISSUE TITLE
Feature request: Begin falling from top and stop until confetti is over

### ISSUE THREAD

**Issue by 00cpxxx** [Agezao/confetti-generator#9]
Hi, thanks for the wonderful and so small library. To make a better visual effect I'm looking for ways to start the animation so the confetti falls from top to bottom instead of start with the whole screen filled. And also a new method, eg stop(), that would stop new confetti so that current confetti keeps falling until no more confetti is on screen.

If that is not clear I can try explaining it better and if you don't think that is useful I can understand and so the issue can be closed ;-)

**Comment by officert** [comment]
this would be dope 👍
